services:
  - type: web
    name: artis-backend
    env: node
    buildCommand: cd backend && npm install && npm run build
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8099
      - key: JWT_SECRET
        generateValue: true
      - key: FRONTEND_URL
        value: https://artis-rust.vercel.app
      - key: DATABASE_URL
        sync: false  # Set this manually in Render dashboard
      - key: GOOGLE_SHEETS_CREDENTIALS_PATH
        value: /etc/secrets/google-sheets-key.json 