services:
  - type: web
    name: artis-backend
    env: node
    buildCommand: cd backend && npm install && npm run build
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: FRONTEND_URL
        value: https://artis-rust.vercel.app
      - key: DATABASE_URL
        fromDatabase:
          name: artis-db
          property: connectionString

databases:
  - name: artis-db
    plan: free
    ipAllowList: [] 